### ISSUE TITLE
[문서 QA] QR 코드 생성기> 다크 모드 화면에서 QR 코드 확인 불가능

### ISSUE THREAD

**Issue by binchoo** [binchoo/paimonganyu-doc#18]
**보고 사례:**
1. 윈도우11> 운영체제 수준에서 다크 모드 활성
2. QR 코드 생성기> QR 생성
3. 2의 QR 코드를 확인할 수 없는 현상을 겪습니다.

**재현 스텝:**
윈도우 11을 사용하고 있지 않으므로 엣지 브라우저를 사용해 다음과 같이 재현합니다.
1. 엣지 브라우저> `edge://flags/`로 이동
2. `dark mode` 검색> `Auto Dark Mode for Web Contents` 항목을 `Enabled`로 설정

![image](https://user-images.githubusercontent.com/15683098/179285076-5b80e256-b54a-42b2-bd68-98b252727b4a.png)

3. QR 코드 생성기> QR 생성
<img src='https://user-images.githubusercontent.com/15683098/179285325-c62e76fe-f581-45d6-b202-c12300278a65.gif' width=720 height=500 />
보고 사례와 동일하게 현상이 재현됩니다.

**To-be:**
일단은 QR 전부가 하얗게 나오는 걸 보니, 다크모드에서 검정색 path의 렌더링을 하얗게 해 버리는 걸로 예상되네요.
따라서 QR 코드 색상을 푸른색 등으로 변경하면 괜찮을지요?

@KLumy 님께 고견을

**Comment by binchoo** [comment]
## `FF0000`
![image](https://user-images.githubusercontent.com/15683098/179291719-f7027bdf-ce79-402d-9d40-3b0059ca2ce1.png)
![image](https://user-images.githubusercontent.com/15683098/179291737-f922cb6f-60ee-46aa-aaf6-a303b16f5999.png)
눈아픔

## `264265`
![image](https://user-images.githubusercontent.com/15683098/179291859-b4580670-2ab0-4867-95dc-c51ed5986d65.png)
![image](https://user-images.githubusercontent.com/15683098/179291897-070df44c-9132-4684-8c78-21e1d4a9a475.png)
푸른 계열은 또 옅은 하늘색으로 변경되어 버림 😠

**Comment by binchoo** [comment]
검정 이외의 QR 색을 일방적으로 정해 버리기는 곤란한 듯.
- 색각 이상자 분께 인지 부담을 주거나
- 모니터의 색해상도나 스마트폰 카메라 성능에 의해 QR을 인지하지 못할 가능성도 올라감.

➡️ 유저가 모달에서 색깔을 변경할 수 있도록, 색 토글들을 추가하는 것은 어떨지?
➡️ 다크모드에 영향을 받지 않도록, 벡터 말고 비트맵을 생성할 수 있다면?

**Comment by vincent-kk** [comment]
@binchoo 님 의견대로 SVG에서 비트맵으로 변경하였습니다~
성공적으로 해결되었네요 👏
